trigger: none

pool:
  name: Default

variables:
- name: terraformVersion
  value: latest
- name: tf_dir
  value: Resource group
- name: bkstrgrg
  value: rgdevops
- name: bkstrg
  value: rgdevops
- name: bkcontainer
  value: tfstate
- name: bkstrgkey
  value: devpipeline.terraform.tfstate

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: $(terraformVersion)
          - task: TerraformTask@5
            displayName: "init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Subscription 1(2ccbb89e-86b6-41f1-819f-b04014248457)'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
          - task: TerraformTask@5
            displayName: 'validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    dependsOn: tfvalidate
    condition: succeeded()
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: $(terraformVersion)
          - task: TerraformTask@5
            displayName: "init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Subscription 1(2ccbb89e-86b6-41f1-819f-b04014248457)'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Subscription 1(2ccbb89e-86b6-41f1-819f-b04014248457)'
          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Subscription 1(2ccbb89e-86b6-41f1-819f-b04014248457)'