trigger: none

pool:
  name: Default

variables:
  terraformVersion: '4.37.0'
  tf_dir: 'Resource group'
  bkstrgrg: 'rgdevops'
  bkstrg: 'rgdevops'
  bkcontainer: 'tfstate'
  bkstrgkey: 'devpipeline.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: $(terraformVersion)
          